# Generated by Django 4.2.6 on 2023-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
